name: Pipeline prix bourse

on:
  schedule:
    # Tous les jours à 20:00 UTC (~21h/22h Europe/Paris selon l’heure d’été)
    - cron: "0 21 * * *"
  workflow_dispatch: {}

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance tiingo pandas tensorflow numpy ta matplotlib xgboost scikit-learn

      - name: Run pipeline script (collecte + nettoyage + signaux)
        env:
          TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
        run: |
          python donne_collectes_nettoye.py

# ÉTAPE 2 : Cerveau Hybride (Génère final_hybrid_predictions.csv)
      - name:  Analyse Hybride (Sniper)
        run: python predict_final_hybrid.py

    # ÉTAPE 3 : Cerveau Prix (Génère final_price_predictions.csv)
      - name:  Prédiction des Prix (Visionnaire)
        run: python train_price_predictor.py

    # ÉTAPE 4 : Fusion pour l'Interface (Génère latest_signals.csv)
      - name:  Génération des Signaux Interface
        run: python signals.py

    # ÉTAPE 5 : Sauvegarde
      - name:  Commit & Push
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add data/*.csv data/*.png
          git commit -m " Daily AI Update" || exit 0
          git push
          else
            echo "Aucun changement à committer."
          fi
