name: Pipeline prix bourse

on:
  schedule:
    # Tous les jours à 20:00 UTC (~21h/22h Europe/Paris selon l’heure d’été)
    - cron: "0 20 * * *"
  workflow_dispatch: {}

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance tiingo pandas numpy ta matplotlib xgboost scikit-learn

      - name: Run pipeline script (collecte + nettoyage + signaux)
        env:
          TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
        run: |
          python donne_collectes_nettoye.py

      - name: Run global backtest (25k€ sur 5 entreprises)
        run: |
          python backtest_global.py
      - name: Run evaluate baselines (dummy)
        run: |
          python evaluate_baselines.py
      - name: Run entrainement Xgboost
        run: |
          python predict_final_hybrid.py
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "warrenshamir10@gmail.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add data
            git commit -m "Auto: update prix + backtest $(date -u +"%Y-%m-%d %H:%M:%S")"
            git push
          else
            echo "Aucun changement à committer."
          fi
